var ioc={
	config:{
		type:'redis.clients.jedis.JedisPoolConfig',
		fields:{ 
			maxActive:2000,
			maxIdle:3,
			maxWait:60000,
			testOnBorrow:true,
			testOnReturn:true
		} 
	},
	pool:{
		type:'redis.clients.jedis.JedisPool',
		args:[{refer:"config"},"172.16.1.104",6379,20000,"platform"]
	},
	omPool:{
		type:'redis.clients.jedis.JedisPool',
		args:[{refer:"config"},"172.16.1.102",6379,20000,"platform"]
	}
	,
	ds:{
		type:'com.alibaba.druid.pool.DruidDataSource',
		fields:{
				url:'jdbc:mysql://172.16.1.104:8966/platform',  
				username:'platform',
				password:'platform',
				initialSize:5,
				minIdle:3,
				maxActive:1050,
				maxWait:30000,
				timeBetweenEvictionRunsMillis:6000,
				minEvictableIdleTimeMillis:30001,
				poolPreparedStatements:false,
				maxPoolPreparedStatementPerConnectionSize:20, 
				filters:'stat'
		}
	},
	infDao:{
		type:'org.nutz.dao.impl.NutDao',
		args:[{refer:"ds"}]
	} 
	
}